/******************************************************************************
 *
 * SiFive Cryptographic Library (SCL)
 *
 ******************************************************************************
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ******************************************************************************/

/**
 * @file sifive_hca-0.5.x.h
 * @brief
 *
 * @copyright Copyright (c) 2020 SiFive, Inc
 * @copyright SPDX-License-Identifier: MIT
 */

#ifndef SIFIVE_HCA_0_5_X_H
#define SIFIVE_HCA_0_5_X_H

//! @cond Doxygen_Suppress

// hasAES
#define HCA_HAS_AES
// hasAESMAC
#define HCA_HAS_AESMAC
// hasSHA
#define HCA_HAS_SHA
// hasTRNG
#define HCA_HAS_TRNG

// METAL_<REGISTER_NAME>_<FIELD_NAME>_OFFSET => number of bits into
// <REGISTER_NAME> METAL_<REGISTER_NAME>_<FIELD_NAME>_MASK => bit width

/*
 * HCA_REGISTER_CR
 */
#define HCA_REGISTER_CR_IFIFOTGT_OFFSET 0UL
#define HCA_REGISTER_CR_IFIFOTGT_MASK 1UL

#define HCA_REGISTER_CR_IFIFOEMPTY_OFFSET 1UL
#define HCA_REGISTER_CR_IFIFOEMPTY_MASK 1UL

#define HCA_REGISTER_CR_IFIFOFULL_OFFSET 2UL
#define HCA_REGISTER_CR_IFIFOFULL_MASK 1UL

#define HCA_REGISTER_CR_OFIFOEMPTY_OFFSET 3UL
#define HCA_REGISTER_CR_OFIFOEMPTY_MASK 1UL

#define HCA_REGISTER_CR_OFIFOFULL_OFFSET 4UL
#define HCA_REGISTER_CR_OFIFOFULL_MASK 1UL

#define HCA_REGISTER_CR_ENDIANNESS_OFFSET 5UL
#define HCA_REGISTER_CR_ENDIANNESS_MASK 1UL

#define HCA_REGISTER_CR_CRYPTODIE_OFFSET 8UL
#define HCA_REGISTER_CR_CRYPTODIE_MASK 1UL

#define HCA_REGISTER_CR_OFIFOIE_OFFSET 9UL
#define HCA_REGISTER_CR_OFIFOIE_MASK 1UL

#define HCA_REGISTER_CR_DMADIE_OFFSET 10UL
#define HCA_REGISTER_CR_DMADIE_MASK 1UL

#define HCA_REGISTER_CR_CRYPTODIS_OFFSET 12UL
#define HCA_REGISTER_CR_CRYPTODIS_MASK 1UL

#define HCA_REGISTER_CR_OFIFOIS_OFFSET 13UL
#define HCA_REGISTER_CR_OFIFOIS_MASK 1UL

#define HCA_REGISTER_CR_DMADIS_OFFSET 14UL
#define HCA_REGISTER_CR_DMADIS_MASK 1UL

#define HCA_REGISTER_CR_IFIFOCNT_OFFSET 16UL
#define HCA_REGISTER_CR_IFIFOCNT_MASK 63UL

#define HCA_REGISTER_CR_AESFIFOCNT_OFFSET 24UL
#define HCA_REGISTER_CR_AESFIFOCNT_MASK 63UL

/*
 * HCA_REGISTER_AES_CR
 */
#define HCA_REGISTER_AES_CR_MODE_OFFSET 0UL
#define HCA_REGISTER_AES_CR_MODE_MASK 7UL

#define HCA_REGISTER_AES_CR_KEYSZ_OFFSET 4UL
#define HCA_REGISTER_AES_CR_KEYSZ_MASK 3UL

#define HCA_REGISTER_AES_CR_PROCESS_OFFSET 6UL
#define HCA_REGISTER_AES_CR_PROCESS_MASK 1UL

#define HCA_REGISTER_AES_CR_INIT_OFFSET 7UL
#define HCA_REGISTER_AES_CR_INIT_MASK 1UL

#define HCA_REGISTER_AES_CR_DTYPE_OFFSET 8UL
#define HCA_REGISTER_AES_CR_DTYPE_MASK 1UL

#define HCA_REGISTER_AES_CR_CCMT_OFFSET 9UL
#define HCA_REGISTER_AES_CR_CCMT_MASK 7UL

#define HCA_REGISTER_AES_CR_CCMQ_OFFSET 12UL
#define HCA_REGISTER_AES_CR_CCMQ_MASK 7UL

#define HCA_REGISTER_AES_CR_BUSY_OFFSET 16UL
#define HCA_REGISTER_AES_CR_BUSY_MASK 1UL

/*
 * HCA_REGISTER_AES_ALLEN
 */
#define HCA_REGISTER_AES_ALEN_0_OFFSET 0UL
#define HCA_REGISTER_AES_ALEN_0_MASK 4294967295UL

#define HCA_REGISTER_AES_ALEN_1_OFFSET 32UL
#define HCA_REGISTER_AES_ALEN_1_MASK 536870911UL

/*
 * HCA_REGISTER_AES_PLDLEN
 */
#define HCA_REGISTER_AES_PLDLEN_0_OFFSET 0UL
#define HCA_REGISTER_AES_PLDLEN_0_MASK 4294967295UL

#define HCA_REGISTER_AES_PLDLEN_1_OFFSET 32UL
#define HCA_REGISTER_AES_PLDLEN_1_MASK 536870911UL

/*
 * HCA_REGISTER_AES_KEY
 */
#define HCA_REGISTER_AES_KEY_0_OFFSET 0UL
#define HCA_REGISTER_AES_KEY_0_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_1_OFFSET 32UL
#define HCA_REGISTER_AES_KEY_1_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_2_OFFSET 64UL
#define HCA_REGISTER_AES_KEY_2_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_3_OFFSET 96UL
#define HCA_REGISTER_AES_KEY_3_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_4_OFFSET 128UL
#define HCA_REGISTER_AES_KEY_4_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_5_OFFSET 160UL
#define HCA_REGISTER_AES_KEY_5_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_6_OFFSET 192UL
#define HCA_REGISTER_AES_KEY_6_MASK 4294967295UL

#define HCA_REGISTER_AES_KEY_7_OFFSET 224UL
#define HCA_REGISTER_AES_KEY_7_MASK 4294967295UL

/*
 * HCA_REGISTER_AES_INITV
 */
#define HCA_REGISTER_AES_INITV_0_OFFSET 0UL
#define HCA_REGISTER_AES_INITV_0_MASK 4294967295UL

#define HCA_REGISTER_AES_INITV_1_OFFSET 32UL
#define HCA_REGISTER_AES_INITV_1_MASK 4294967295UL

#define HCA_REGISTER_AES_INITV_2_OFFSET 64UL
#define HCA_REGISTER_AES_INITV_2_MASK 4294967295UL

#define HCA_REGISTER_AES_INITV_3_OFFSET 96UL
#define HCA_REGISTER_AES_INITV_3_MASK 4294967295UL

/*
 * HCA_REGISTER_SHA_CR
 */
#define HCA_REGISTER_SHA_CR_MODE_OFFSET 0UL
#define HCA_REGISTER_SHA_CR_MODE_MASK 3UL

#define HCA_REGISTER_SHA_CR_INIT_OFFSET 2UL
#define HCA_REGISTER_SHA_CR_INIT_MASK 1UL

#define HCA_REGISTER_SHA_CR_BUSY_OFFSET 16UL
#define HCA_REGISTER_SHA_CR_BUSY_MASK 1UL

/*
 * HCA_REGISTER_FIFO_IN
 */
#define HCA_REGISTER_FIFO_IN_DATA_0_OFFSET 0UL
#define HCA_REGISTER_FIFO_IN_DATA_0_MASK 4294967295UL

#define HCA_REGISTER_FIFO_IN_DATA_1_OFFSET 32UL
#define HCA_REGISTER_FIFO_IN_DATA_1_MASK 4294967295UL

/*
 * HCA_REGISTER_AES_OUT
 */
#define HCA_REGISTER_AES_OUT_AES_OUT_0_OFFSET 0UL
#define HCA_REGISTER_AES_OUT_AES_OUT_0_MASK 4294967295UL

#define HCA_REGISTER_AES_OUT_AES_OUT_1_OFFSET 32UL
#define HCA_REGISTER_AES_OUT_AES_OUT_1_MASK 4294967295UL

/*
 * HCA_REGISTER_AES_AUTH
 */
#define HCA_REGISTER_AES_AUTH_0_OFFSET 0UL
#define HCA_REGISTER_AES_AUTH_0_MASK 4294967295UL

#define HCA_REGISTER_AES_AUTH_1_OFFSET 32UL
#define HCA_REGISTER_AES_AUTH_1_MASK 4294967295UL

#define HCA_REGISTER_AES_AUTH_2_OFFSET 64UL
#define HCA_REGISTER_AES_AUTH_2_MASK 4294967295UL

#define HCA_REGISTER_AES_AUTH_3_OFFSET 96UL
#define HCA_REGISTER_AES_AUTH_3_MASK 4294967295UL

/*
 * HCA_REGISTER_HASH
 */
#define HCA_REGISTER_HASH_0_OFFSET 0UL
#define HCA_REGISTER_HASH_0_MASK 4294967295UL

#define HCA_REGISTER_HASH_1_OFFSET 32UL
#define HCA_REGISTER_HASH_1_MASK 4294967295UL

#define HCA_REGISTER_HASH_2_OFFSET 64UL
#define HCA_REGISTER_HASH_2_MASK 4294967295UL

#define HCA_REGISTER_HASH_3_OFFSET 96UL
#define HCA_REGISTER_HASH_3_MASK 4294967295UL

#define HCA_REGISTER_HASH_4_OFFSET 128UL
#define HCA_REGISTER_HASH_4_MASK 4294967295UL

#define HCA_REGISTER_HASH_5_OFFSET 160UL
#define HCA_REGISTER_HASH_5_MASK 4294967295UL

#define HCA_REGISTER_HASH_6_OFFSET 192UL
#define HCA_REGISTER_HASH_6_MASK 4294967295UL

#define HCA_REGISTER_HASH_7_OFFSET 224UL
#define HCA_REGISTER_HASH_7_MASK 4294967295UL

#define HCA_REGISTER_HASH_8_OFFSET 256UL
#define HCA_REGISTER_HASH_8_MASK 4294967295UL

#define HCA_REGISTER_HASH_9_OFFSET 288UL
#define HCA_REGISTER_HASH_9_MASK 4294967295UL

#define HCA_REGISTER_HASH_10_OFFSET 320UL
#define HCA_REGISTER_HASH_10_MASK 4294967295UL

#define HCA_REGISTER_HASH_11_OFFSET 352UL
#define HCA_REGISTER_HASH_11_MASK 4294967295UL

#define HCA_REGISTER_HASH_12_OFFSET 384UL
#define HCA_REGISTER_HASH_12_MASK 4294967295UL

#define HCA_REGISTER_HASH_13_OFFSET 416UL
#define HCA_REGISTER_HASH_13_MASK 4294967295UL

#define HCA_REGISTER_HASH_14_OFFSET 448UL
#define HCA_REGISTER_HASH_14_MASK 4294967295UL

#define HCA_REGISTER_HASH_15_OFFSET 480UL
#define HCA_REGISTER_HASH_15_MASK 4294967295UL

/*
 * HCA_REGISTER_TRNG_CR
 */
#define HCA_REGISTER_TRNG_CR_HTSTART_OFFSET 0UL
#define HCA_REGISTER_TRNG_CR_HTSTART_MASK 1UL

#define HCA_REGISTER_TRNG_CR_RNDIRQEN_OFFSET 1UL
#define HCA_REGISTER_TRNG_CR_RNDIRQEN_MASK 1UL

#define HCA_REGISTER_TRNG_CR_HTIRQEN_OFFSET 2UL
#define HCA_REGISTER_TRNG_CR_HTIRQEN_MASK 1UL

#define HCA_REGISTER_TRNG_CR_BURSTEN_OFFSET 3UL
#define HCA_REGISTER_TRNG_CR_BURSTEN_MASK 1UL

/*
 * HCA_REGISTER_TRNG_SR
 */
#define HCA_REGISTER_TRNG_SR_RNDRDY_OFFSET 0UL
#define HCA_REGISTER_TRNG_SR_RNDRDY_MASK 1UL

#define HCA_REGISTER_TRNG_SR_SRCS_OFFSET 1UL
#define HCA_REGISTER_TRNG_SR_SRCS_MASK 1UL

#define HCA_REGISTER_TRNG_SR_HTR_OFFSET 2UL
#define HCA_REGISTER_TRNG_SR_HTR_MASK 1UL

#define HCA_REGISTER_TRNG_SR_HTS_OFFSET 3UL
#define HCA_REGISTER_TRNG_SR_HTS_MASK 1UL

/*
 * HCA_REGISTER_TRNG_DATA
 */
#define HCA_REGISTER_TRNG_DATA_DATA_OFFSET 0UL
#define HCA_REGISTER_TRNG_DATA_DATA_MASK 4294967295UL

/*
 * HCA_REGISTER_TRNG_TRIM
 */
#define HCA_REGISTER_TRNG_TRIM_LOCK_OFFSET 31UL
#define HCA_REGISTER_TRNG_TRIM_LOCK_MASK 1UL

/*
 * HCA_REGISTER_DMA_CR
 */
#define HCA_REGISTER_DMA_CR_START_OFFSET 0UL
#define HCA_REGISTER_DMA_CR_START_MASK 1UL

#define HCA_REGISTER_DMA_CR_BUSY_OFFSET 8UL
#define HCA_REGISTER_DMA_CR_BUSY_MASK 1UL

#define HCA_REGISTER_DMA_CR_RDALIGNERR_OFFSET 9UL
#define HCA_REGISTER_DMA_CR_RDALIGNERR_MASK 1UL

#define HCA_REGISTER_DMA_CR_WRALIGNERR_OFFSET 10UL
#define HCA_REGISTER_DMA_CR_WRALIGNERR_MASK 1UL

#define HCA_REGISTER_DMA_CR_RESPERR_OFFSET 11UL
#define HCA_REGISTER_DMA_CR_RESPERR_MASK 1UL

#define HCA_REGISTER_DMA_CR_LEGALERR_OFFSET 12UL
#define HCA_REGISTER_DMA_CR_LEGALERR_MASK 1UL

/*
 * HCA_REGISTER_DMA_LEN
 */
#define HCA_REGISTER_DMA_LEN_LEN_OFFSET 0UL
#define HCA_REGISTER_DMA_LEN_LEN_MASK 268435455UL

/*
 * HCA_REGISTER_DMA_SRC
 */
#define HCA_REGISTER_DMA_SRC_SRC_0_OFFSET 0UL
#define HCA_REGISTER_DMA_SRC_SRC_0_MASK 4294967295UL

/*
 * HCA_REGISTER_DMA_DEST
 */
#define HCA_REGISTER_DMA_DEST_DEST_0_OFFSET 0UL
#define HCA_REGISTER_DMA_DEST_DEST_0_MASK 4294967295UL

/*
 * HCA_REGISTER_HCA_REV
 */
#define HCA_REGISTER_HCA_REV_PATCHREV_OFFSET 0UL
#define HCA_REGISTER_HCA_REV_PATCHREV_MASK 15UL

#define HCA_REGISTER_HCA_REV_MINORREV_OFFSET 4UL
#define HCA_REGISTER_HCA_REV_MINORREV_MASK 15UL

#define HCA_REGISTER_HCA_REV_MAJORREV_OFFSET 8UL
#define HCA_REGISTER_HCA_REV_MAJORREV_MASK 15UL

/*
 * HCA_REGISTER_AES_REV
 */
#define HCA_REGISTER_AES_REV_PATCHREV_OFFSET 0UL
#define HCA_REGISTER_AES_REV_PATCHREV_MASK 15UL

#define HCA_REGISTER_AES_REV_MINORREV_OFFSET 4UL
#define HCA_REGISTER_AES_REV_MINORREV_MASK 15UL

#define HCA_REGISTER_AES_REV_MAJORREV_OFFSET 8UL
#define HCA_REGISTER_AES_REV_MAJORREV_MASK 15UL

#define HCA_REGISTER_AES_REV_TYPE_OFFSET 12UL
#define HCA_REGISTER_AES_REV_TYPE_MASK 15UL

/*
 * HCA_REGISTER_SHA_REV
 */
#define HCA_REGISTER_SHA_REV_PATCHREV_OFFSET 0UL
#define HCA_REGISTER_SHA_REV_PATCHREV_MASK 15UL

#define HCA_REGISTER_SHA_REV_MINORREV_OFFSET 4UL
#define HCA_REGISTER_SHA_REV_MINORREV_MASK 15UL

#define HCA_REGISTER_SHA_REV_MAJORREV_OFFSET 8UL
#define HCA_REGISTER_SHA_REV_MAJORREV_MASK 15UL

#define HCA_REGISTER_SHA_REV_TYPE_OFFSET 12UL
#define HCA_REGISTER_SHA_REV_TYPE_MASK 15UL

/*
 * HCA_REGISTER_TRNG_REV
 */
#define HCA_REGISTER_TRNG_REV_PATCHREV_OFFSET 0UL
#define HCA_REGISTER_TRNG_REV_PATCHREV_MASK 15UL

#define HCA_REGISTER_TRNG_REV_MINORREV_OFFSET 4UL
#define HCA_REGISTER_TRNG_REV_MINORREV_MASK 15UL

#define HCA_REGISTER_TRNG_REV_MAJORREV_OFFSET 8UL
#define HCA_REGISTER_TRNG_REV_MAJORREV_MASK 15UL

#define HCA_REGISTER_TRNG_REV_TYPE_OFFSET 12UL
#define HCA_REGISTER_TRNG_REV_TYPE_MASK 15UL

//! @endcond

#endif
